#!/usr/bin/env python

import hashlib, sys, os.path

if len(sys.argv) == 1:
    input = sys.stdin
    name = "-"
elif len(sys.argv) == 2:
    input = open(sys.argv[1])
    name = sys.argv[1]
else:
    print >>sys.stderr, "confusing arguments"
    sys.exit(1)

h = hashlib.new(os.path.basename(sys.argv[0][:-3]))
while True:
    d = input.read(1024)
    if not d:
        break
    h.update(d)
print "%s  %s" % (h.hexdigest(), name)
